spring:
  profiles:
    include: oauth

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/reserve
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      properties:
        hibernate:
          format_sql: true
          show_sql: true



