spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 550412050057-cheuurhcdk6dtg61sj97g0l25jeh7h96.apps.googleusercontent.com
            client-secret: fNUM7jArr0jqBiRKdtNultOn
            scope:
              - email
              - profile
